### ISSUE TITLE
treinamento consultoria

### ISSUE THREAD

**Issue by livioweb** [mozgbrasil/heroku-magento#1]
Se t fazem este tipo de trabalho, falem ?

**Comment by mozgbrasil** [comment]
Bom dia

Venho atuando com o Magento 1 desde 2008 prestando serviços desde a concepção do projeto mas com foco em desenvolvimento de módulos e templates

Envie sua necessidade para o e-mail 

suporte@mozg.com.br

Ou se preferir me mande mensagem no WhatsApp

+55 11 977072339
